### ISSUE TITLE
The binary search tree isn't balanced

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/rmw#212]
https://github.com/theimpossibleastronaut/rmw/blob/e5939a55beafd0503ee362a4bffbe1f388e8b53e/src/bst.c#L2

https://github.com/theimpossibleastronaut/rmw/blob/e5939a55beafd0503ee362a4bffbe1f388e8b53e/src/restore_rmw.c#L372

The binary search tree used by restore_select() isn't balanced (because code to do so hasn't been added, not because of a bug).

**Comment by andy5995** [comment]
I'm not sure if much would be gained by balancing. The binary tree is created and it outputs the list, but because it doesn't get "searched" later, I'm just not too sure adding the code to balance the list first would provide much benefit.

**Comment by Jammyjamjamman** [comment]
If we want to balance the tree without too much modification to the code, I would recommend implementing an AVL tree.
See: https://www.geeksforgeeks.org/avl-tree-set-1-insertion/

Another option is to use a B+ tree. This is a good option when storing a very big tree on a hard disk, because it's very shallow. Finding a node in a shallow tree requires (on average) accessing less nodes than a deep tree, so less disk reads, so it's faster.
See: https://www.geeksforgeeks.org/introduction-of-b-tree-2/

**Comment by andy5995** [comment]
> I'm not sure if much would be gained by balancing. The binary tree is created and it outputs the list, but because it doesn't get "searched" later, I'm just not too sure adding the code to balance the list first would provide much benefit.

Time to close this...
