### ISSUE TITLE
Add an option to force empty the trash immediately

### ISSUE THREAD

**Issue by Jammyjamjamman** [theimpossibleastronaut/rmw#229]
Currently, an environment variable is required to empty the trash immediately:

        RMWTRASH=empty rmw -fg

I think this would look better if it was an option, like --empty/ e (as @andy5995 suggested):

        rmw -fge

This would be a considerably more dangerous option, so I see why this option is not so easily available.

**Comment by andy5995** [comment]
Let's require 2 f's, like what's needed for [removing files that are -w](https://github.com/theimpossibleastronaut/rmw/blob/77260724ae42d3154ad17eefadca4cc6e015ddb5/src/purging_rmw.c#L83)

And you'll see in rmw.c how easy it is to add both the -e and --empty options.

The RMWTRASH=fake-year can still be used for testing I think. Maybe we'll think of a better alternative solution for that in the future though.

**Comment by Jammyjamjamman** [comment]
Yeah I think external vars are fine for setting development options.

I can try and fix this at some point xD, although my C programming knowledge is a little rusty...

**Comment by andy5995** [comment]
@Jammyjamjamman you won't have any major trouble with the patch, trust me. When you get to it, it'll probably take you less than 30 minutes.

Just look at the section in main where the command line options are parsed. You're just going to add another one.

`const char *const short_options = "hvc:goz:lstuwVfir";`

The colons in that line means that the option takes an argument. e.g. "-c alternate config file".. that's why there's a ":" after the c but hardly any of the other ones.

You'll clearly see where to add a "want_empty" var....  Because it'll only be used for the purge() function, you'll declare it in main and it won't be global, so you'll need to add a second argument to the purge() definition and prototype so "want_empty" can be passed from main() to purge()

And replace the code in purge() where currently RMWTRASH=empty is with a check for "want_empty"...

**Comment by andy5995** [comment]
> You'll clearly see where to add a "want_empty" var.... Because it'll only be used for the purge() function, you'll declare it in main and it won't be global, so you'll need to add a second argument to the purge() definition and prototype so "want_empty" can be passed from main() to purge()

On second thought, I think it'll be safe enough declare it and initialize it here:

https://github.com/theimpossibleastronaut/rmw/blob/f3c5ec36f2b2e7775d603af8f0ca5b9c75253491/src/rmw.c#L78

You'll add the condition here, depending on what the user wants

https://github.com/theimpossibleastronaut/rmw/blob/f3c5ec36f2b2e7775d603af8f0ca5b9c75253491/src/rmw.c#L138-L199

The you can use the 'extern' keyword to use it in purging_rmw.c, which means you don't have to add an extra parameter to the purge() function.

https://github.com/theimpossibleastronaut/rmw/blob/f3c5ec36f2b2e7775d603af8f0ca5b9c75253491/src/purging_rmw.c#L266
