### ISSUE TITLE
Wildcards do not work for "-z" option

### ISSUE THREAD

**Issue by Jammyjamjamman** [theimpossibleastronaut/rmw#272]
The help claims you can use wildcards with `-z` option, but this does not work for me. Wildcards only work for deleting files for me.

**Comment by andy5995** [comment]
@Jammyjamjamman , thanks for testing that feature. It works under certain condtions; please see the notes in the [README](https://github.com/theimpossibleastronaut/rmw/blob/master/README.md), under the heading for the -z option.

But now that you mention it, some changes need to be made. I'd guess the UX you had would be quite common.

Best thing would be that -z would work in all cases, which.. probably wouldn't be too difficult, I just hadn't given it any thought yet. Probably easier to add code to make it so, rather than trying to adjust docs and help output! xD

**Comment by andy5995** [comment]
Here's what the README says about using -z

```
== -z, --restore ==

To restore a file, or multiple files, specify the path to them in in the
<WASTE>/files folder (wildcards ok).
e.g. 'rmw -z ~/.local/share/Trash/files/foo*'

Files can also be restored using only the basename, from within any directory.
NOTE: That feature will not process wildcards unless the user is in a
<WASTE>/files folder and the filespec actually exists in the present working
directory.
```
