### ISSUE TITLE
Please consider returning a non 0 code when calling interactive move

### ISSUE THREAD

**Issue by ccoVeille** [theimpossibleastronaut/rmw#435]
The interactive mode is not yet implemented, and might never will 

The code is 2 years old

https://github.com/theimpossibleastronaut/rmw/blob/4a19330014cce68423b46ac149f85264b36a5fb4/src/parse_cli_options.c#L339-L341

And I have no problem with that.

My problem is that the `rmw` is sometimes used as a direct replacement for `rm`

I would expect an existing code, either a local script or something

```shell
rm -i bar || whatever
```

This code is only an example to explain.

`whatever` will never be called if rmw has replaced rm

I would have expected returning an error as you do here

https://github.com/theimpossibleastronaut/rmw/blob/4a19330014cce68423b46ac149f85264b36a5fb4/src/parse_cli_options.c#L360-L361

**Comment by ccoVeille** [comment]
I've just understood the current implementation of interactive is deleting the file anyway.

So I'm unsure if there is a real need about what I asked for. But maybe, I'm unsure having a simple info and not respecting the interactive behavior might be a problem.

Please comment and close if you think my request was irrelevant.

**Comment by andy5995** [comment]
> I've just understood the current implementation of interactive is deleting the file anyway.

Not deleting, but the file gets moved to a Waste or Trash folder. Or stated another way, it gets rmw'ed ;)


> 
> So I'm unsure if there is a real need about what I asked for. But maybe, I'm unsure having a simple info and not respecting the interactive behavior might be a problem.

It's probably best if people don't expect rmw to act as rm, since they do almost completely different things. I have some comments about this in the FAQ at https://theimpossibleastronaut.com/rmw-website/faq.html

> 
> Please comment and close if you think my request was irrelevant.

I think the discussion is relevant and I appreciate your interest and feedback. There may be some changes I could consider that would make things more clear to other people in the future.

For example, I could remove handling the '-i' option completely (you linked to that code). Usage of '-i' is not in the docs or the '--help' output anyway. If I removed handling it, there would only be a brief error message if someone used it, stating it's an invalid option.

As I recall my thinking, I believed having an interactive option for rmw wouldn't be very beneficial because files don't get permanently deleted (purged) until after they "expire" (see 'expire_age' in the config file).

Another option is that I could keep the code the way it is. It seems you found out very quickly how '-i' is expected to work with rmw. How long have you been using rmw? Do you have any other suggestions for how to handle (or not handle) '-i'?

**Comment by ccoVeille** [comment]
Thanks for your detailed reply.

I think returning an error would be the best. It would be have like any invalid option.

I mean it's not implemented in an interactive way, it puts the file in the trash, yes. But the user asked for something interactive and didn't get it.

rmw -i it doesn't behave the same way as rm would, and adding interactive mode would be overkill to rmw. I like how you kept the code "simple". I'm not even sure how many people are using the interactive mode with rm.

So I would say, return an error when someone try to use interactive mode.

My opinion is only one among others, maybe you could open a discussion among users. Or decide by your own.

**Comment by ccoVeille** [comment]
For anyone interested in reading this issue. The --interactive/-i argument is now raising an error as any unknown/unsupported argument
